name: taxi_lakehouse
version: 1.0.0
config-version: 2

profile: taxi_lakehouse

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

on-run-start:
  - "{{ configure_minio_access() }}"

models:
  taxi_lakehouse:
    silver:
      +materialized: table
    gold:
      +materialized: view
